### ISSUE TITLE
Not worked anymore

### ISSUE THREAD

**Issue by Dreyk007** [EmilioK97/pydeepl#12]
I got "too many requests" error from the start. And after that i can not use anymore web-version. So looks like my IP got banned right after i started the script first time.

**Comment by dajor** [comment]
>>> import pydeepl
>>> 
>>> sentence = 'I like turtles.'
>>> from_language = 'EN'
>>> to_language = 'ES'
>>> 
>>> translation = pydeepl.translate(sentence, to_language, from_lang=from_language)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daniel/dev/Fellow/translate/venv/lib/python3.6/site-packages/pydeepl/pydeepl.py", line 97, in translate
    raise TranslationError('DeepL call resulted in a unknown result.')
pydeepl.pydeepl.TranslationError: DeepL call resulted in a unknown result.
>>> print(translation)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'translation' is not defined
>>> 
>>> # Using auto-detection
... translation = pydeepl.translate(sentence, to_language)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/daniel/dev/Fellow/translate/venv/lib/python3.6/site-packages/pydeepl/pydeepl.py", line 97, in translate
    raise TranslationError('DeepL call resulted in a unknown result.')
pydeepl.pydeepl.TranslationError: DeepL call resulted in a unknown result.

**Comment by kasu207** [comment]
> > > > import pydeepl
> > > > sentence = 'I like turtles.'
> > > > from_language = 'EN'
> > > > to_language = 'ES'
> > > > translation = pydeepl.translate(sentence, to_language, from_lang=from_language)
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/Users/daniel/dev/Fellow/translate/venv/lib/python3.6/site-packages/pydeepl/pydeepl.py", line 97, in translate
> > > > raise TranslationError('DeepL call resulted in a unknown result.')
> > > > pydeepl.pydeepl.TranslationError: DeepL call resulted in a unknown result.
> > > > print(translation)
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > NameError: name 'translation' is not defined
> > > > # Using auto-detection
> 
> ... translation = pydeepl.translate(sentence, to_language)
> Traceback (most recent call last):
> File "", line 2, in 
> File "/Users/daniel/dev/Fellow/translate/venv/lib/python3.6/site-packages/pydeepl/pydeepl.py", line 97, in translate
> raise TranslationError('DeepL call resulted in a unknown result.')
> pydeepl.pydeepl.TranslationError: DeepL call resulted in a unknown result.

I get the same error.

**Comment by fcolecumberri** [comment]
+1
